import { FilterConfig } from './types';

export const planetsFilters: Record<string, FilterConfig> = {
  population: {
    type: 'range',
    values: [
      {
        name: 'unknown',
        range: [0, 0],
      },
      {
        name: 'small',
        range: [0, 1000000],
      },
      {
        name: 'medium',
        range: [1000000, 1000000000],
      },
      {
        name: 'large',
        range: [1000000000, Infinity],
      },
    ],
  },
  diameter: {
    type: 'range',
    values: [
      {
        name: 'unknown',
        range: [0, 0],
      },
      {
        name: 'small',
        range: [0, 10000],
      },
      {
        name: 'medium',
        range: [10000, 15000],
      },

      {
        name: 'large',
        range: [15000, 20000],
      },
      {
        name: 'huge',
        range: [20000, Infinity],
      },
    ],
  },
  climate: {
    type: 'string',
    values: [
      'arid',
      'artic',
      'artificial temperate',
      'frigid',
      'frozen',
      'hot',
      'humid',
      'moist',
      'murky',
      'polluted',
      'rocky',
      'subartic',
      'superheated',
      'temperate',
      'tropical',
      'unknown',
      'windy',
    ],
  },
  terrain: {
    type: 'string',
    values: [
      'acid pools',
      'airless asteroid',
      'ash',
      'barren',
      'bogs',
      'canyons',
      'caves',
      'cities',
      'cityscape',
      'cliffs',
      'desert',
      'deserts',
      'fields',
      'forests',
      'fungus forests',
      'gas giant',
      'glaciers',
      'grass',
      'grasslands',
      'grassy hills',
      'hills',
      'ice canyons',
      'ice caves',
      'islands',
      'jungle',
      'jungles',
      'lakes',
      'lava rivers',
      'mesas',
      'mountain',
      'mountain ranges',
      'mountains',
      'ocean',
      'oceans',
      'plains',
      'plateaus',
      'rainforests',
      'reefs',
      'rivers',
      'rock',
      'rock arches',
      'rocky',
      'rocky canyons',
      'rocky deserts',
      'rocky islands',
      'savanna',
      'savannahs',
      'savannas',
      'scrublands',
      'seas',
      'sinkholes',
      'swamp',
      'swamps',
      'toxic cloudsea',
      'tundra',
      'unknown',
      'urban',
      'valleys',
      'verdant',
      'vines',
      'volcanoes',
    ],
  },
};
