import { FilterConfig } from './types';

export const starshipsFilters: Record<string, FilterConfig> = {
  manufacturer: {
    type: 'string',
    values: [
      'Allanteen Six shipyards',
      'Alliance Underground Engineering',
      'Botajef Shipyards',
      'Corellian Engineering Corporation',
      'Cygnus Spaceworks',
      'Cyngus Spaceworks',
      'Feethan Ottraw Scalable Assemblies',
      'Fondor Shipyards',
      'Free Dac Volunteers Engineering corps.',
      'Gallofree Yards',
      'Gwori Revolutionary Industries',
      'Hoersch-Kessel Drive',
      'Huppla Pasa Tisc Shipwrights Collective',
      'Imperial Department of Military Research',
      'Inc',
      'Inc.',
      'Incom Corporation',
      'Incorporated',
      'Koensayr Manufacturing',
      'Kuat Drive Yards',
      'Kuat Systems Engineering',
      'Mon Calamari shipyards',
      'Nubia Star Drives',
      'Rendili StarDrive',
      'Republic Sienar Systems',
      'Rothana Heavy Engineering',
      'Sienar Fleet Systems',
      'Slayn & Korpil',
      'Subpro Corporation',
      'Theed Palace Space Vessel Engineering Corps',
      'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives',
    ],
  },
  hyperdrive_rating: {
    type: 'string',
    values: [
      '0.5',
      '0.6',
      '0.7',
      '0.9',
      '1.0',
      '1.5',
      '1.8',
      '2.0',
      '3.0',
      '4.0',
      '6',
      'unknown',
    ],
  },
  MGLT: {
    type: 'string',
    values: [
      '10',
      '20',
      '40',
      '50',
      '60',
      '70',
      '75',
      '80',
      '91',
      '100',
      '105',
      '120',
      'unknown',
    ],
  },
  starship_class: {
    type: 'string',
    values: [
      'Armed government transport',
      'Assault Starfighter',
      'Deep Space Mobile Battlestation',
      'Diplomatic barge',
      'Droid control ship',
      'Escort ship',
      'Light freighter',
      'Medium transport',
      'Patrol craft',
      'Space Transport',
      'Space cruiser',
      'Star Cruiser',
      'Star Destroyer',
      'Star dreadnought',
      'Starfighter',
      'assault ship',
      'assault starfighter',
      'capital ship',
      'corvette',
      'cruiser',
      'freighter',
      'landing craft',
      'star destroyer',
      'starfighter',
      'transport',
      'yacht',
    ],
  },
};
